name: Java CI con Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Instalar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar y testear con Maven
      run: mvn -B clean verify

    - name: Crear release en GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        body: "Build automático generado por CI"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Crear release en GitHub y subir JAR
  uses: softprops/action-gh-release@v1
  with:
    tag_name: v1.0.${{ github.run_number }}
    name: "Release v1.0.${{ github.run_number }}"
    body: "Build automático generado por CI"
    files: target/*.jar
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

